# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 'Leon的博客'
author : 'Leon'
description: 'php知识分享,php技术交流,技术博客' # write a nice description for your blog
baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://www.acier.cn' # the base hostname & protocol for your site http://www.example.com
# google_analytics: 'UA-XXXXXX-X'
twitter_username: 'wl236179666'
email: 'leon236@163.com'
#weibo_username: 'charlie1013'
github_username: 'wl236179666'
# Build settings
markdown: kramdown

permalink: '/:title/'

gems: [jekyll-paginate]

paginate: 10
